CREATE TABLE [dbo].[PARTI_NO](
	[PARTIID] [int] IDENTITY(1,1) NOT NULL,
	[TARIH] [datetime] NULL,
	[TABLENAME] [nvarchar](50) NULL,
	[SIRANO] [nvarchar](10) NULL,
 CONSTRAINT [PK_PARTI_NO] PRIMARY KEY CLUSTERED 
(
	[PARTIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 50) ON [PRIMARY]
) ON [PRIMARY]

GO

