ALTER TABLE ARTETIKETDETAY ADD ADET1 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET2 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET3 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET4 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET5 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET6 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET7 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET8 INT NULL
ALTER TABLE ARTETIKETDETAY ADD ADET9 INT NULL

ALTER TABLE ARTETIKETDETAY ADD DARA1 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA2 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA3 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA4 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA5 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA6 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA7 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA8 INT NULL
ALTER TABLE ARTETIKETDETAY ADD DARA9 INT NULL

