CREATE TABLE [dbo].[PARTI_NO_TERAZI](
	[TERAZIID] [int] IDENTITY(1,1) NOT NULL,
	[PARTINO] [nvarchar](10) NOT NULL,
	[STOKID] [int] NOT NULL,
	[MIKTAR] [float] NOT NULL,
	[TARIH] [smalldatetime] NOT NULL CONSTRAINT [DF_PARTI_NO_TERAZI_TARIH]  DEFAULT (CONVERT([date],getdate(),(0))),
	[SAAT] [nvarchar](8) NOT NULL CONSTRAINT [DF_PARTI_NO_TERAZI_SAAT]  DEFAULT (CONVERT([time],getdate(),(0))),
	[KOLIICINDE] [bit] NOT NULL CONSTRAINT [DF_PARTI_NO_TERAZI_KOLIICINDE]  DEFAULT ((0)),
	[KOLIGRUPID] [int] NOT NULL CONSTRAINT [DF_PARTI_NO_TERAZI_KOLIGRUPID]  DEFAULT ((0)),
 CONSTRAINT [PK_PARTI_NO_TERAZI] PRIMARY KEY CLUSTERED 
(
	[TERAZIID] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 50) ON [PRIMARY]
) ON [PRIMARY]

GO