CREATE TABLE [dbo].[ARTETIKETDETAY](
	[STOKID] [int] NOT NULL,
	[EK1] [nvarchar](max) NULL,
	[EK2] [nvarchar](max) NULL,
	[EK3] [nvarchar](max) NULL,
	[EK4] [nvarchar](max) NULL,
	[EK5] [nvarchar](max) NULL,
	[EK6] [nvarchar](max) NULL,
	[EK7] [nvarchar](max) NULL,
	[EK8] [nvarchar](max) NULL,
	[EK9] [nvarchar](max) NULL,
	[EK10] [nvarchar](max) NULL,
 CONSTRAINT [PK_ARTETIKETDETAY] PRIMARY KEY CLUSTERED 
(
	[STOKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 50) ON [PRIMARY],
 CONSTRAINT [IX_ARTETIKETDETAY_STOKID] UNIQUE NONCLUSTERED 
(
	[STOKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
